version: '3.8'
services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=django-insecure-%qg+3of26rt=d*%z=wu8_+!46_z&-l5ncuf82(9l&idssqu4#d
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:14.0
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=metauser
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=postgres_db

volumes:
  postgres_data:
